name: Automated E2E Testing

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests with Electron
        uses: cypress-io/github-action@v4
        with:
          browser: electron
        env:
          email: ${{ secrets.email }}
          password: ${{ secrets.password }}
          VITE_API_HOST_URL: ${{ secrets.VITE_API_HOST_URL }}
          VITE_API_KEY: ${{ process.VITE_API_KEY }}
